base_url = "https://billygoat.dev"
title = "billygoat.dev"
description = "Straight from the goat's mouth."
theme = "tale-zola"

compile_sass = true
build_search_index = false


taxonomies = [{ name="tags" }]

[markdown]
highlight_code = true

[extra]
author = "Billy"

# Menu items
[[extra.menu]]
name = "Posts"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "about"

[extra.footer]
start_year = "2020"  # start year of the site
end_year = "2021"    # end year of the site
info = "The information on the footer."